CREATE TABLE Division (
	DivisionID UNIQUEIDENTIFIER CONSTRAINT PK_Division PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL
)

CREATE TABLE Employee (
	EmployeeID UNIQUEIDENTIFIER CONSTRAINT PK_Employee PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL,
	DivisionID UNIQUEIDENTIFIER CONSTRAINT FK_Employee_Division FOREIGN KEY REFERENCES Division NOT NULL
)
